server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081

swagger:
  resourcePackage: pl.jojczykp.cdstore

albums:
  profile: cdstore
  endpoint: http://cdstore-dynamodb:8000

tracks:
  zookeeperQuorum: cdstore-hbase
  zookeeperClientPort: 2181
  hbaseMaster: cdstore-hbase:60000
