server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081

swagger:
  resourcePackage: pl.jojczykp.cdstore

albums:
  profile: cdstore
  endpoint: https://dynamodb.eu-west-1.amazonaws.com

tracks:
  zookeeperQuorum: ip-172-31-34-1
  zookeeperClientPort: 2181
  hbaseMaster: ip-172-31-34-1:60000
